* Rakefile
** rake 
   [[http://docs.ruby-lang.org/ja/2.2.0/library/rake.html][library rake (Ruby 2.2.0)]] はビルドツール

   [[http://www2s.biglobe.ne.jp/~idesaku/sss/tech/rake/][rakeの例]]
   
** Rakefile

#+name:rakefile
#+begin_src ruby :tangle Rakefile :noweb yes
# coding:utf-8

def myhome
  path = `pwd`.chomp.split("/").reverse
  depth = path.index("org")
  [depth, path[0..depth].reverse]
end
  
depth,path = myhome
MYHOME = "./"+"../"*depth
ORG = "#{MYHOME}org/"
SITE = "#{MYHOME}/docs/"
path.shift
DIR = path.join("/")
tests = ["test-card.rb", 
         "test-deck.rb",
         "test-hand.rb",
         "test-player.rb",
        ]

task :default => :test

task :test do
  tests.each do |test_file|
    sh "ruby -I./src test/#{test_file}"
  end
end
#+end_src

#+BEGIN_SRC sh  :results output :dir babel :session sh
rake test

#+END_SRC

#+RESULTS:
#+begin_example

esut0001-U% rake test
ruby -I./src test/test-card.rb
[38;5;46;1m.[0m[38;5;46;1m.[0m[38;5;46;1m.[0m

Finished in 0.001237106 seconds.
[38;5;46;1m------[0m
3 tests, 8 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
passed
[38;5;46;1m------[0m
2425.01 tests/s, 6466.71 assertions/s
ruby -I./src test/test-deck.rb
[38;5;46;1m.[0m[38;5;46;1m.[0m[38;5;46;1m.[0m

Finished in 0.001974801 seconds.
[38;5;46;1m------[0m
3 tests, 108 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
passed
[38;5;46;1m------[0m
1519.14 tests/s, 54689.05 assertions/s
ruby -I./src test/test-hand.rb
[38;5;46;1m.[0m

Finished in 0.000699579 seconds.
[38;5;46;1m------[0m
1 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
passed
[38;5;46;1m------[0m
1429.43 tests/s, 1429.43 assertions/s
ruby -I./src test/test-player.rb
[38;5;226mE[0m

Error: [48;5;16;38;5;226;1mtest_player_new(TestDeck)[0m: NoMethodError: undefined method `hand' for nil:NilClass
test/test-player.rb:14:in `test_player_new'
     11:   def test_player_new
     12:     @p = Player.new("hoge")
     13:     assert_equal("hoge",  @p.name)
14:     assert_equal(Hand.new, @h.hand)[0m
     15:   end
     16: 
     17: end



Finished in 0.001412339 seconds.
[38;5;226m------[0m
1 tests, 1 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
passed
[38;5;226m------[0m
708.05 tests/s, 708.05 assertions/s
rake aborted!
Command failed with status (1): [ruby -I./src test/test-player.rb...]
'
/home/staff/suzuki/COMM/Lects/meta-ruby/site/lects/poker/babel/Rakefile:12:in `each'
'
test
(See full trace by running task with --trace)
#+end_example

