# coding:utf-8

def myhome
  path = `pwd`.chomp.split("/").reverse
  depth = path.index("org")
  [depth+1, path[0..depth].reverse]
end
  
depth,path = myhome
MYHOME = "../"*depth
ORG = "#{MYHOME}org/"
SITE = "#{MYHOME}docs/"
path.shift
DIR = path.join("/")


SRCS = ["index.org", "contents.org", "resume.org", "response.org"]

task :default => "index.html"

file "index.html" => SRCS do
  sh "org2html index.org"
end

task :deploy => "index.html" do
  sh "mkdir -p #{SITE}#{DIR}"
  sh "cp -p index.html #{SITE}#{DIR}"
end
