
# src/Makefile 
.PHONY: clean
CFLAGS = -g -c -fPIC -I. 
LDFLAGS = -lc

libcard.a: card.o cards.o
	rm -f $@
	ar r $@ $^

card.o: card.c card.h
	gcc $< $(CFLAGS)

# (2015.12.08) cards.o: cards.o card.h 
cards.o: cards.c card.h 
	gcc $< $(CFLAGS)

clean: 
	rm -f *.o *.so *~ \#* *.gch
