oall:
	make index.html
	make prog-2015.html
	make openning.html
	make ta.html

.SUFFIXES: .org .html
.org.html: ../info/common-header.org 
	org2html $<

index.html:

prog-2015.html:

openning.html:

ta.html:

.PHONY: clean
clean:
	rm -f *.html
