# coding:utf-8
# coding:utf-8
require 'date'

SUBDIRS = ["lects", "org-docs", "memos", "supplement"]
EXCLS = ["log.org", "contents.org", "Makefile.org", "Rakefile.org"]
ORGS = FileList["*.org"] - EXCLS
HTMLS = ORGS.ext(".html")
NOW = DateTime.now.to_s

ORGS.each do |org|
  html = File.basename(org, ".org")+".html"
  depends = `org_dependency.rb #{org}`.split(",")
  rule html => depends 
end

def myhome
  path = `pwd`.chomp.split("/").reverse
  depth = path.index("org")
  [depth+1, path[0..depth].reverse]
end

def org_sub_dir
  (Dir.glob("*/*.org").map do |f| File.dirname(f) end).uniq
end
  
depth,path = myhome

MYHOME = "../"*depth
ORG = "#{MYHOME}org/"
SITE = "#{MYHOME}docs/"
path.shift
DIR = path.join("/")

def deploy(file, dir)
  p "deploying #{dir}#{file}"
  sh "mkdir -p #{dir}"
  File.open("#{dir}/#{file}", "w") do |target| 
    all = File.read(file).gsub("http://", "https://")
    all.gsub!('//www.pirilampo.org', '//wiki.cis.iwate-u.ac.jp/~suzuki/org-html-theme')
    target.write(all)
  end

  sh "git add #{dir}/#{file}"
  sh "git commit -m deploy_#{NOW} #{dir}/#{file}"

end

rule ".html" => ".org" do |t|
  sh "org2html #{t.prerequisites.join(' ')}"
  deploy(t.name, "#{SITE}/#{DIR}")
end

task :default => [:org2html, :subdirs]

task :org2html => HTMLS do

  p "git push"
  sh "git push"
  
end

task :subdirs do
  org_sub_dir.each do |subdir|
    Dir.chdir(subdir) do
      puts `pwd`
      sh "rake"
    end
  end
end    

task :subdirs_install_rakefile do
  org_sub_dir.each do |subdir|
    Dir.chdir(subdir) do
      puts `pwd`
      sh "cp ../Rakefile.org ."
      sh "cp ../Rakefile ."
      sh "rake subdirs_install_rakefile"
    end
  end
end    
