* お知らせ

** レポートの回収  <2016-10-25 火>

*** 「課題:card_display問題を始める」のレポートを回収します。

   各自の，~/progs/card_display/first/ を回収します。そこには，
   下記のファイルがあることを想定しています：

     - ~/progs/card_display/first/simple.org

       simple_*.c を作成する際に考えたことをまとめる。

     - ~/progs/card_display/first/simple_*.c

       段階的に作成したソースプログラム達。

     - ~/progs/card_display/first/Makefile_*

       各段階のソースプログラムをコンパイルするためのMakefile達。


*** 確認方法

    今回のレポートは，~suzuki/progss/collected_srcs/1/の下に回収します。

    ~suzuki/progss/collected_srcs/1/自分のログイン名/first の下を確認
    してください。


** [[./index.org][講義サイト]] のタブに補足を追加しました <2016-10-25 火>

Emacs や Org-mode のこと，ガイダンスでふれたプログラム開発に関すること
を，[[./index.org][講義サイト]] の補足タブとして追加しました。

とりあえずの処置です。


** リアルタイムストリーミングを試してみましょう  <2016-10-25 火>

萩原さんが，調べてくれました。試してみましょう:   

*** 3.1. 送信側 (先生)

#+BEGIN_SRC sh :export both

ffmpeg -f x11grab -s 1920x1080 -framerate 15 -i :0.0 -c:v libx264 -preset fast -pix_fmt yuv420p -s 1280x720 -threads 0 -f sap sap://224.0.0.255 &

#+END_SRC

*** 3.2. 受信側 (学生)
- vlcを起動します:
  ： % vlc 

- 「表示」->「プレイリスト」->「ローカルネットワーク」->「ネットワークス
トリーム(SAP)」->「No Name」をダブルクリック

- そこそこ待つ

- 表示サイズは受信側でも変更可能

*** キャプチャのみ(先生)

#+BEGIN_SRC sh
ffmpeg -f x11grab -s 1920x1080 -framerate 15 -i :0.0 ~suzuki/progs/lects/03.mp4
#+END_SRC

#+RESULTS:

二番目のモニタをキャプチャしたい場合はオプションを"-i :0.0+1920,0"にしてください． 
キャプチャの終了はC-cです．

** card_display/first/simple.c の解説 <2016-10-12 水>

[[./index.org][講義サイト]] の [[./memos.org][雑メモ]] タブから見られるようにしました。

Emacs で見るには，~suzuki/prog.git/org/memos/simple.org が最新です。

~suzuki/progs/card_display/first/ に下に，C のソースとMakefileがありま す。

** org-mode の文書の見方 <2016-10-12 水>

simple.org は org-mode で書いてあります。 Emacs で開いて，見出しで，
TAB または SHIFT+TAB を打つと，下位の文書 構造を展開縮小されます。


** 講義サイトの雑メモが開かなかったわけ <2016-10-12 水>

org-mode 文書を HTML に変換すると，数式マークアップのレンダリングのた
めに， MathML.js を使いますが，昨日 は何故か https://orgmode.org から
ダウンロードできなかったようです。

mathml.org おすすめの
https://cdn.mathjax.org/mathjax/latest/MathJax.js からダウンロードする
よう書き換えました。


** ガイダンスの説明について <2016-10-11 火>

初回のガイダンスがわかりにくかったようです。すみません。

説明を省いたと感じた人も多
かたようですが，ガイダンスでは，こんな事をやりますと，項目とその入口へ
の情報を羅列したにすぎません。省略したのではありません。

*** 講義で教えること <2016-10-11 火>

重要なことをまとめると, 次のようになります:

主テーマは，*プログラムの設計と開発のこと* です。

そのために次のことを，体験的に学びます:

- モジュラー・プログラミングのこと
- テストとテストによる開発のこと
- 設計，開発について文書を作成すること (このために，org-mode を使うこ
  とを *推奨* しています。)

*** 前提とする知識

そのためには，次の知識が必要です:
- プログラム言語とプログラミング
- コンパイルと実行のこと，
- ライブラリのこと，
- make と Makefileのこと，
- Emacs のこと
- シェルと Linux のこと

これらは，講義にとっては，副次的なことですが，
プログラミングにとっては，全て必須のことです。
しかし，教えられていなかったり，難かしかったり，経験不足などで，
知識が不足していますよね。

僕(先生)は，どの知識が不足しているのか，はっきりとは把握していませんが，
基本的なことは，教えられていて，わかっている (いてほしい) と考えています。
そういう立場で講義を作っています。

わかっていない事，わからない事は，僕に伝えてください。講義中に指摘して
ください。歓迎します。

*** 講義資料

新らしいカリキュラムになって，3回目の講義です。皆さんの状況が，だいぶ
分ってきましたが，講義のための資料作りにはかなり時間がかかります。
講義内容全部を整合させるのには，もっと時間がかかります。

状況に対応した資料を作る努力はしているつもりですが，配慮や時間や技術が
足りません。

不足している資料やおかしな所は，指摘してください。

不足している情報は，自分で調べるようにも，してください。

** 講義の実施時間について <2016-10-11 火> 

#+BEGIN_QUOTE
金先生とお話して，2:30 以降も端末室を使えることになりました。
#+END_QUOTE

あらためて提案します。

演習を伴なう (むしろ演習が主な) 講義なので，90分の時間内で，
講義と演習を終ることが，例年，できません。

- 講義内容の説明は，2:30 までに終りにします。

- 講義中の課題は次週までの宿題とします。

- 2:30~ 自主的に課題に取り組む時間とし，
  3:00 までは TA さんが対応してくれ，
  それ以降は，((s-:)) が適宜対応します。

どうでしょうか？


** 講義資料について <2016-10-11 火>

- [[./org-docs.org][資料]] :: 
     基本，講義する内容です。教科書的な資料です。

- [[./supplement.org][説明]] ::
     資料への補足説明です。昨年度，徐々に書いたもので，今年度，資料に反映させ
     た方がいいかもしれませんが，まだ見直していません。

- [[./memos.org][雑メモ]] :: 
     昨年の講義の進行中に，思い付いて書いたメモです。要整理です。

- [[./lects.org][講義]] ::
     おしらせ，講義の情報，講義の記録などです。



- [[http://wiki.cis.iwate-u.ac.jp/~suzuki/lects/prog/][2015]] ::
     2015年度のソフトウェア構成論の講義の全てです。


** ホームディレクトリのパーミションについて

 進行状況の確認や，レポート提出のために，~/progs の中を閲覧，回収したい
 と思っています。

 ~/progs の中を，鈴木 (((s-:))) が見られるように設定してもらえませんか？

   : chmod o+rx ~
   : chmod -R o+rx ~/progs

** 2016-10-18 休講します。
   SCHEDULED: <2016-10-02 日>

  ((s-:)) ネンリンピック長崎 サッカー出場のため
   

** 2016-10-04 開講します。 
   SCHEDULED: <2016-10-02 日>

   
   








