# coding:utf-8

SRCS = Dir.glob("*.html")

def myhome
  path = `pwd`.chomp.split("/").reverse
  depth = path.index("org")
  [depth+1, path[0..depth].reverse]
end
  
depth,path = myhome
MYHOME = "../"*depth
ORG = "#{MYHOME}org/"
SITE = "#{MYHOME}docs/"
path.shift
DIR = path.join("/")

task :default => [:deploy, :subdirs]

task :deploy do 
  SRCS.each do |html|
    sh "mkdir -p #{SITE}#{DIR}"
    sh "cp -p #{html} #{SITE}#{DIR}"
  end
end

task :subdirs do
  SRCS.delete("index.html")
  SRCS.each do |html|
    subdir = File.basename(html,".html")
    unless File.exist?("#{subdir}/Rakefile") 
      sh "cp Rakefile #{subdir}/"
    end
    p Dir.pwd
    sh "rake"
  end
end    
