# coding:utf-8

ORGS = FileList["*.orgs"]
HTMLS = ORGS.ext(".html")

def myhome
  path = `pwd`.chomp.split("/").reverse
  depth = path.index("org")
  [depth+1, path[0..depth].reverse]
end
  
depth,path = myhome
MYHOME = "../"*depth
ORG = "#{MYHOME}org/"
SITE = "#{MYHOME}docs/"
path.shift
DIR = path.join("/")

rule ".html" => ".org" do |t|
   sh "org2html #{t.souce}"
   sh "mkdir -p $(SITE)/$(DIR)"
   sh "cp #{t.name} $(SITE)/$(DIR)"
   p "cp #{t.name} $(SITE)/$(DIR)"
end

task :default => [:org2html, :deploy]

task :org2html => HTMLS 

task :deploy do 
  HTMLS.each do |html|
    sh "mkdir -p #{SITE}#{DIR}"
    sh "cp -p #{html} #{SITE}#{DIR}"
  end
end

task :subdirs do
  HTMLS.delete("index.html")
  HTMLS.each do |html|
    subdir = File.basename(html,".html")
    unless File.exist?("#{subdir}/Rakefile") 
      sh "cp Rakefile #{subdir}/"
    end
    p  Dir.pwd
    Dir.chdir(subdir) do
      sh "rake"
    end
  end
end    
